# Generated by Django 4.1.3 on 2022-11-27 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedjango', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addfilm',
            name='genress',
            field=models.CharField(default=1, max_length=255, verbose_name='Жанр'),
            preserve_default=False,
        ),
    ]
