# Generated by Django 4.1.3 on 2022-11-27 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedjango', '0002_addfilm_genress'),
    ]

    operations = [
        migrations.AddField(
            model_name='addfilm',
            name='url',
            field=models.CharField(default=1, max_length=255, verbose_name='Ссылка'),
            preserve_default=False,
        ),
    ]
