# Generated by Django 4.1.3 on 2022-11-29 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviedjango', '0003_addfilm_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Genress',
        ),
    ]
