# Generated by Django 4.1.3 on 2022-11-30 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedjango', '0005_alter_addfilm_genress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addfilm',
            name='genress',
            field=models.CharField(max_length=255, verbose_name='Жанр'),
        ),
    ]
